### ISSUE TITLE
ffe-icons-react: IconProps interface does not allow for rest parameters

### ISSUE THREAD

**Issue by hdaljord** [SpareBank1/designsystem#860]
## Which package is this issue related to?
ffe-icons-react

#### Describe your issue (screenshots welcome!)
After upgrading ffe-icons-react to 7.2.2 (from 7.0.3, typescript declarations for all icons was added in the 7.1.0) I get a type errors like this

`ERROR in /home/sb1a.sparebank1.no/a500118/git/kundeklient-forsikring-bm/kfb-frontend/src/main/components/Huskeliste/Oppgave.tsx(25,30):
TS2322: Type '{ className: string; }' is not assignable to type 'IntrinsicAttributes & IconProps & { children?: ReactNode; }'.
  Property 'className' does not exist on type 'IntrinsicAttributes & IconProps & { children?: ReactNode; }'.
`

The code:
`
<LyspareIkon className="kfb-icon--sm kfb-icon--blue-royal"/>
`

#### What is the expected behavior? 
As the generated component accepts rest-parameters standard HTML attributes, such as className, should be allowed.

IconProps should probably extend React.HTMLAttributes<HTMLElement> .

**Comment by henrikhermansen** [comment]
@tutturen can you take a look at this?

**Comment by steffenz** [comment]
Hi! :wave:
I recently joined the new design-system team, and figured this might be a good first issue to resolve :smile: 

It seems to me that the most correct attribute to extend is React.SVGAttributes, not React.HTMLAttributes (but I might be wrong here). I tried with both of them, but the latter lacks elements specific to SVG elements. I've created a PR (see mention above this comment).
